Feature/apps 1772 upgrade to log4jv2
Alfresco/alfresco-tas-utility pull request #96
Opened 2022-12-08 08:46 UTC by kavitshah-gl

These changes are for the upgrade to Log4jv2.

2022-12-13 08:51 UTC, dsibilio requested changes

2022-12-13 08:51 UTC, dsibilio commented on samples/consuming-tas-utility/src/test/resources/log4j2.properties
> +#log4j.appender.Console.layout.ConversionPattern=%d{ABSOLUTE} %-5p [%c] %m%n
We should remove commented out configuration with Log4j 1.x syntax.

2022-12-13 08:51 UTC, dsibilio commented on samples/consuming-tas-utility/src/test/resources/log4j2.properties
> +appender.RollingAppender.policies.time.interval = 1
In the original file the rolling strategy was not based on time, but rather on size combined with a max backup count similar to this:

```
###### File appender definition #######
appender.rolling.type=RollingFile
appender.rolling.name=RollingAppender
appender.rolling.fileName=./target/reports/alfresco-tas.log
appender.rolling.filePattern=./target/reports/alfresco-tas.log.%i
appender.rolling.layout.type=PatternLayout
appender.rolling.layout.pattern=[%t] %d{HH:mm:ss} %-5p %c{1}:%L - %replace{%m}{[\r\n]+}{}%n
appender.rolling.policies.type=Policies
appender.rolling.policies.size.type=SizeBasedTriggeringPolicy
appender.rolling.policies.size.size=10MB
appender.rolling.strategy.type=DefaultRolloverStrategy
appender.rolling.strategy.max=10
```

2022-12-13 08:51 UTC, dsibilio commented on samples/consuming-tas-utility/src/test/resources/log4j2.properties
> +appender.ConsoleAppender.layout.pattern=%d{ISO8601} %x %-5p [%c{3}] [%t] %replace{%m}{[\r\n]+}{}%n
Is there a reason why we're changing the layout pattern compared to the original implementation? 

In general I'd expect that we try and keep the patterns that are already present, e.g. in this case: `[%t] %d{HH:mm:ss} %-5p %c{1}:%L - %m%n` whilst replacing the newlines therefore making it: `[%t] %d{HH:mm:ss} %-5p %c{1}:%L - %replace{%m}{[\r\n]+}{}%n`

**Note: this applies to all patterns in the PR.**

2022-12-13 08:51 UTC, dsibilio commented on samples/consuming-tas-utility/src/test/resources/log4j2.properties
> +#log4j.rootLogger=${app.log.root.level}, Console, File
We should remove commented out configuration with Log4j 1.x syntax.

2022-12-13 08:51 UTC, dsibilio commented on samples/consuming-tas-utility/src/test/resources/log4j2.properties
> +appender.TestRollingAppender.strategy.max = 10
This configuration should be largely similar to the one I just proposed earlier as a literal translation of the previous implementation, with minor differences in the file name, appender name, layout pattern structure.

2022-12-13 08:51 UTC, dsibilio commented on src/test/resources/log4j2.properties
> +#log4j.rootLogger=${app.log.root.level}, Console, File
Should be removed.

2022-12-13 08:51 UTC, dsibilio commented on src/test/resources/log4j2.properties
> +#log4j.appender.Console.layout.ConversionPattern=%d{ABSOLUTE} %-5p [%c] %m%n
Should be removed.

2022-12-13 08:51 UTC, dsibilio commented on src/test/resources/log4j2.properties
> +appender.TestRollingAppender.strategy.max = 10
Pretty much same as the previously highlighted configuration translation issue, I believe we weren't faithful in the translation of the configuration and I'm not sure if this was a desired change or not.

2022-12-14 11:03 UTC, dsibilio approved these changes

2022-12-14 11:19 UTC, MohinishSah approved these changes
LGTM

2022-12-14 13:37 UTC, damianujma approved these changes

2022-12-14 13:44 UTC, aonych approved these changes

2022-12-14 13:52 UTC, merged